/**
 * 베트남어 단어 학습 게임 데이터
 * TOPIK 1-2 수준의 동사들을 중심으로 구성
 */

const WORDS = {
  /**
   * 쉬운 난이도 (TOPIK 1-2 빈출 동사)
   */
  easy: [
    {
      vietnamese: 'làm',
      korean: '하다',
      vietnameseExample: 'Tôi làm bài tập mỗi ngày.',
      koreanExample: '저는 매일 숙제를 합니다.',
    },
    {
      vietnamese: 'đi',
      korean: '가다',
      vietnameseExample: 'Tôi đi học mỗi ngày.',
      koreanExample: '저는 매일 학교에 갑니다.',
    },
    {
      vietnamese: 'ăn',
      korean: '먹다',
      vietnameseExample: 'Tôi ăn cơm vào buổi tối.',
      koreanExample: '저는 저녁에 밥을 먹습니다.',
    },
    {
      vietnamese: 'uống',
      korean: '마시다',
      vietnameseExample: 'Tôi thích uống cà phê.',
      koreanExample: '저는 커피 마시는 것을 좋아합니다.',
    },
    {
      vietnamese: 'ngủ',
      korean: '자다',
      vietnameseExample: 'Tôi ngủ lúc 11 giờ tối.',
      koreanExample: '저는 밤 11시에 잡니다.',
    },
    {
      vietnamese: 'học',
      korean: '공부하다',
      vietnameseExample: 'Tôi học tiếng Hàn mỗi ngày.',
      koreanExample: '저는 매일 한국어를 공부합니다.',
    },
    {
      vietnamese: 'xem',
      korean: '보다',
      vietnameseExample: 'Tôi xem phim Hàn Quốc.',
      koreanExample: '저는 한국 영화를 봅니다.',
    },
    {
      vietnamese: 'đến',
      korean: '오다',
      vietnameseExample: 'Anh ấy đến vào lúc 9 giờ.',
      koreanExample: '그는 9시에 옵니다.',
    },
    {
      vietnamese: 'về',
      korean: '돌아오다',
      vietnameseExample: 'Tôi về nhà lúc 6 giờ.',
      koreanExample: '저는 6시에 집에 돌아옵니다.',
    },
    {
      vietnamese: 'mua',
      korean: '사다',
      vietnameseExample: 'Tôi mua sách tiếng Hàn.',
      koreanExample: '저는 한국어 책을 삽니다.',
    },
    {
      vietnamese: 'viết',
      korean: '쓰다',
      vietnameseExample: 'Tôi viết thư cho bạn.',
      koreanExample: '저는 친구에게 편지를 씁니다.',
    },
    {
      vietnamese: 'đọc',
      korean: '읽다',
      vietnameseExample: 'Tôi đọc sách mỗi ngày.',
      koreanExample: '저는 매일 책을 읽습니다.',
    },
    {
      vietnamese: 'nói',
      korean: '말하다',
      vietnameseExample: 'Tôi nói tiếng Hàn.',
      koreanExample: '저는 한국어를 말합니다.',
    },
    {
      vietnamese: 'nghe',
      korean: '듣다',
      vietnameseExample: 'Tôi nghe nhạc K-pop.',
      koreanExample: '저는 K-pop 음악을 듣습니다.',
    },
    {
      vietnamese: 'thích',
      korean: '좋아하다',
      vietnameseExample: 'Tôi thích phim Hàn Quốc.',
      koreanExample: '저는 한국 영화를 좋아합니다.',
    },
    {
      vietnamese: 'gặp',
      korean: '만나다',
      vietnameseExample: 'Tôi gặp bạn vào cuối tuần.',
      koreanExample: '저는 주말에 친구를 만납니다.',
    },
    {
      vietnamese: 'đợi',
      korean: '기다리다',
      vietnameseExample: 'Tôi đợi bạn ở trường.',
      koreanExample: '저는 학교에서 친구를 기다립니다.',
    },
    {
      vietnamese: 'bán',
      korean: '팔다',
      vietnameseExample: 'Cô ấy bán hoa quả.',
      koreanExample: '그녀는 과일을 팝니다.',
    },
    {
      vietnamese: 'giúp',
      korean: '돕다',
      vietnameseExample: 'Tôi giúp bạn học tiếng Hàn.',
      koreanExample: '저는 친구가 한국어를 공부하는 것을 돕습니다.',
    },
    {
      vietnamese: 'cười',
      korean: '웃다',
      vietnameseExample: 'Cô ấy cười rất đẹp.',
      koreanExample: '그녀는 웃는 모습이 매우 예쁩니다.',
    },
    {
      vietnamese: 'khóc',
      korean: '울다',
      vietnameseExample: 'Em bé khóc vì đói.',
      koreanExample: '아기가 배고파서 웁니다.',
    },
    {
      vietnamese: 'hỏi',
      korean: '묻다',
      vietnameseExample: 'Tôi hỏi đường đến trường.',
      koreanExample: '저는 학교까지 가는 길을 물어봅니다.',
    },
    {
      vietnamese: 'dậy',
      korean: '일어나다',
      vietnameseExample: 'Tôi dậy lúc 6 giờ sáng.',
      koreanExample: '저는 아침 6시에 일어납니다.',
    },
    {
      vietnamese: 'cho',
      korean: '주다',
      vietnameseExample: 'Tôi cho bạn quà.',
      koreanExample: '저는 친구에게 선물을 줍니다.',
    },
    {
      vietnamese: 'nhận',
      korean: '받다',
      vietnameseExample: 'Tôi nhận thư từ Hàn Quốc.',
      koreanExample: '저는 한국에서 온 편지를 받습니다.',
    },
    {
      vietnamese: 'mở',
      korean: '열다',
      vietnameseExample: 'Tôi mở cửa sổ.',
      koreanExample: '저는 창문을 엽니다.',
    },
    {
      vietnamese: 'đóng',
      korean: '닫다',
      vietnameseExample: 'Tôi đóng cửa lúc 10 giờ tối.',
      koreanExample: '저는 밤 10시에 문을 닫습니다.',
    },
    {
      vietnamese: 'bật',
      korean: '켜다',
      vietnameseExample: 'Tôi bật đèn vào buổi tối.',
      koreanExample: '저는 저녁에 불을 켭니다.',
    },
    {
      vietnamese: 'tắt',
      korean: '끄다',
      vietnameseExample: 'Tôi tắt tivi trước khi ngủ.',
      koreanExample: '저는 자기 전에 TV를 끕니다.',
    },
    {
      vietnamese: 'đứng',
      korean: '서다',
      vietnameseExample: 'Tôi đứng chờ xe buýt.',
      koreanExample: '저는 서서 버스를 기다립니다.',
    },
    {
      vietnamese: 'ngồi',
      korean: '앉다',
      vietnameseExample: 'Tôi ngồi học tiếng Hàn.',
      koreanExample: '저는 앉아서 한국어를 공부합니다.',
    },
    {
      vietnamese: 'nằm',
      korean: '눕다',
      vietnameseExample: 'Tôi nằm trên giường.',
      koreanExample: '저는 침대에 누워 있습니다.',
    },
    {
      vietnamese: 'nghỉ',
      korean: '쉬다',
      vietnameseExample: 'Tôi nghỉ vào cuối tuần.',
      koreanExample: '저는 주말에 쉽니다.',
    },
    {
      vietnamese: 'gọi',
      korean: '전화하다',
      vietnameseExample: 'Tôi gọi cho bạn tối nay.',
      koreanExample: '저는 오늘 밤에 친구에게 전화합니다.',
    },
    {
      vietnamese: 'tìm',
      korean: '찾다',
      vietnameseExample: 'Tôi tìm chìa khóa.',
      koreanExample: '저는 열쇠를 찾습니다.',
    },
    {
      vietnamese: 'đặt',
      korean: '예약하다',
      vietnameseExample: 'Tôi đặt bàn ở nhà hàng.',
      koreanExample: '저는 식당에서 테이블을 예약합니다.',
    },
    {
      vietnamese: 'yêu',
      korean: '사랑하다',
      vietnameseExample: 'Tôi yêu gia đình.',
      koreanExample: '저는 가족을 사랑합니다.',
    },
    {
      vietnamese: 'sống',
      korean: '살다',
      vietnameseExample: 'Tôi sống ở Seoul.',
      koreanExample: '저는 서울에 삽니다.',
    },
    {
      vietnamese: 'chơi',
      korean: '놀다',
      vietnameseExample: 'Trẻ em chơi trong công viên.',
      koreanExample: '아이들이 공원에서 놉니다.',
    },
    {
      vietnamese: 'mặc',
      korean: '입다',
      vietnameseExample: 'Tôi mặc áo ấm vào mùa đông.',
      koreanExample: '저는 겨울에 따뜻한 옷을 입습니다.',
    },
    {
      vietnamese: 'cởi',
      korean: '벗다',
      vietnameseExample: 'Tôi cởi áo khoác khi vào nhà.',
      koreanExample: '저는 집에 들어갈 때 겉옷을 벗습니다.',
    },
    {
      vietnamese: 'rửa',
      korean: '씻다',
      vietnameseExample: 'Tôi rửa mặt mỗi sáng.',
      koreanExample: '저는 매일 아침 세수를 합니다.',
    },
    {
      vietnamese: 'tắm',
      korean: '목욕하다',
      vietnameseExample: 'Tôi tắm mỗi ngày.',
      koreanExample: '저는 매일 목욕합니다.',
    },
    {
      vietnamese: 'bơi',
      korean: '수영하다',
      vietnameseExample: 'Tôi bơi vào mùa hè.',
      koreanExample: '저는 여름에 수영합니다.',
    },
    {
      vietnamese: 'chạy',
      korean: '달리다',
      vietnameseExample: 'Tôi chạy buổi sáng.',
      koreanExample: '저는 아침에 달리기를 합니다.',
    },
    {
      vietnamese: 'nhảy',
      korean: '춤추다',
      vietnameseExample: 'Cô ấy nhảy rất đẹp.',
      koreanExample: '그녀는 춤을 매우 아름답게 춥니다.',
    },
    {
      vietnamese: 'hát',
      korean: '노래하다',
      vietnameseExample: 'Tôi hát bài hát tiếng Hàn.',
      koreanExample: '저는 한국 노래를 부릅니다.',
    },
    {
      vietnamese: 'vẽ',
      korean: '그리다',
      vietnameseExample: 'Tôi vẽ tranh vào cuối tuần.',
      koreanExample: '저는 주말에 그림을 그립니다.',
    },
    {
      vietnamese: 'chụp',
      korean: '사진찍다',
      vietnameseExample: 'Tôi chụp ảnh ở Seoul.',
      koreanExample: '저는 서울에서 사진을 찍습니다.',
    },
    {
      vietnamese: 'dùng',
      korean: '사용하다',
      vietnameseExample: 'Tôi dùng từ điển tiếng Hàn.',
      koreanExample: '저는 한국어 사전을 사용합니다.',
    },
    {
      vietnamese: 'quên',
      korean: '잊다',
      vietnameseExample: 'Tôi quên chìa khóa.',
      koreanExample: '저는 열쇠를 잊었습니다.',
    },
    {
      vietnamese: 'nhớ',
      korean: '기억하다',
      vietnameseExample: 'Tôi nhớ tên bạn.',
      koreanExample: '저는 친구의 이름을 기억합니다.',
    },
    {
      vietnamese: 'hiểu',
      korean: '이해하다',
      vietnameseExample: 'Tôi hiểu tiếng Hàn.',
      koreanExample: '저는 한국어를 이해합니다.',
    },
    {
      vietnamese: 'biết',
      korean: '알다',
      vietnameseExample: 'Tôi biết địa chỉ nhà bạn.',
      koreanExample: '저는 친구의 집 주소를 알고 있습니다.',
    },
    {
      vietnamese: 'cần',
      korean: '필요하다',
      vietnameseExample: 'Tôi cần giúp đỡ.',
      koreanExample: '저는 도움이 필요합니다.',
    },
    {
      vietnamese: 'muốn',
      korean: '원하다',
      vietnameseExample: 'Tôi muốn đi Hàn Quốc.',
      koreanExample: '저는 한국에 가고 싶습니다.',
    },
    {
      vietnamese: 'phải',
      korean: '해야 하다',
      vietnameseExample: 'Tôi phải học tiếng Hàn.',
      koreanExample: '저는 한국어를 공부해야 합니다.',
    },
    {
      vietnamese: 'có',
      korean: '있다',
      vietnameseExample: 'Tôi có một quyển sách.',
      koreanExample: '저는 책 한 권이 있습니다.',
    },
    {
      vietnamese: 'ghét',
      korean: '싫어하다',
      vietnameseExample: 'Tôi ghét thức ăn cay.',
      koreanExample: '저는 매운 음식을 싫어합니다.',
    },
    {
      vietnamese: 'sửa',
      korean: '고치다',
      vietnameseExample: 'Tôi sửa lỗi sai.',
      koreanExample: '저는 실수를 고칩니다.',
    },
    {
      vietnamese: 'gửi',
      korean: '보내다',
      vietnameseExample: 'Tôi gửi thư cho bạn.',
      koreanExample: '저는 친구에게 편지를 보냅니다.',
    },
    {
      vietnamese: 'ghi',
      korean: '기록하다',
      vietnameseExample: 'Tôi ghi chú bài học.',
      koreanExample: '저는 수업 내용을 기록합니다.',
    },
    {
      vietnamese: 'hẹn',
      korean: '약속하다',
      vietnameseExample: 'Tôi hẹn gặp bạn ngày mai.',
      koreanExample: '저는 내일 친구를 만나기로 약속했습니다.',
    },
    {
      vietnamese: 'mang',
      korean: '가지고 가다',
      vietnameseExample: 'Tôi mang sách đến trường.',
      koreanExample: '저는 책을 학교에 가지고 갑니다.',
    },
    {
      vietnamese: 'để',
      korean: '두다',
      vietnameseExample: 'Tôi để điện thoại trên bàn.',
      koreanExample: '저는 전화기를 탁자 위에 둡니다.',
    },
    {
      vietnamese: 'mời',
      korean: '초대하다',
      vietnameseExample: 'Tôi mời bạn đến nhà.',
      koreanExample: '저는 친구를 집에 초대합니다.',
    },
    {
      vietnamese: 'chúc',
      korean: '축하하다',
      vietnameseExample: 'Tôi chúc bạn sinh nhật vui vẻ.',
      koreanExample: '저는 친구의 생일을 축하합니다.',
    },
    {
      vietnamese: 'bắt',
      korean: '잡다',
      vietnameseExample: 'Tôi bắt xe buýt đi học.',
      koreanExample: '저는 버스를 타고 학교에 갑니다.',
    },
    {
      vietnamese: 'lái',
      korean: '운전하다',
      vietnameseExample: 'Tôi lái xe đến công ty.',
      koreanExample: '저는 차를 운전해서 회사에 갑니다.',
    },
    {
      vietnamese: 'đậu',
      korean: '주차하다',
      vietnameseExample: 'Tôi đậu xe ở bãi đỗ xe.',
      koreanExample: '저는 주차장에 차를 주차합니다.',
    },
    {
      vietnamese: 'đổi',
      korean: '교환하다',
      vietnameseExample: 'Tôi đổi tiền ở ngân hàng.',
      koreanExample: '저는 은행에서 돈을 환전합니다.',
    },
    {
      vietnamese: 'trả',
      korean: '반환하다',
      vietnameseExample: 'Tôi trả sách cho thư viện.',
      koreanExample: '저는 도서관에 책을 반납합니다.',
    },
    {
      vietnamese: 'thuê',
      korean: '대여하다',
      vietnameseExample: 'Tôi thuê xe đạp ở công viên.',
      koreanExample: '저는 공원에서 자전거를 대여합니다.',
    },
    {
      vietnamese: 'kiểm',
      korean: '검사하다',
      vietnameseExample: 'Tôi kiểm hành lý trước khi đi.',
      koreanExample: '저는 출발 전에 짐을 확인합니다.',
    },
    {
      vietnamese: 'xuất',
      korean: '출발하다',
      vietnameseExample: 'Tàu xuất phát lúc 9 giờ sáng.',
      koreanExample: '기차는 오전 9시에 출발합니다.',
    },
    {
      vietnamese: 'đỗ',
      korean: '합격하다',
      vietnameseExample: 'Tôi đỗ kỳ thi TOPIK.',
      koreanExample: '저는 TOPIK 시험에 합격했습니다.',
    },
    {
      vietnamese: 'rơi',
      korean: '떨어지다',
      vietnameseExample: 'Chìa khóa rơi xuống đất.',
      koreanExample: '열쇠가 바닥에 떨어졌습니다.',
    },
    {
      vietnamese: 'bay',
      korean: '날다',
      vietnameseExample: 'Tôi bay đến Seoul tuần sau.',
      koreanExample: '저는 다음 주에 서울로 날아갑니다.',
    },
    {
      vietnamese: 'cắt',
      korean: '자르다',
      vietnameseExample: 'Tôi cắt tóc ngày mai.',
      koreanExample: '저는 내일 머리를 자릅니다.',
    },
    {
      vietnamese: 'giặt',
      korean: '빨래하다',
      vietnameseExample: 'Tôi giặt quần áo vào cuối tuần.',
      koreanExample: '저는 주말에 옷을 빨래합니다.',
    },
    {
      vietnamese: 'ủi',
      korean: '다림질하다',
      vietnameseExample: 'Tôi ủi áo sơ mi.',
      koreanExample: '저는 셔츠를 다림질합니다.',
    },
    {
      vietnamese: 'sưởi',
      korean: '따뜻하게 하다',
      vietnameseExample: 'Tôi sưởi phòng vào mùa đông.',
      koreanExample: '저는 겨울에 방을 따뜻하게 합니다.',
    },
    {
      vietnamese: 'lau',
      korean: '닦다',
      vietnameseExample: 'Tôi lau bàn sau khi ăn.',
      koreanExample: '저는 식사 후에 테이블을 닦습니다.',
    },
    {
      vietnamese: 'quét',
      korean: '쓸다',
      vietnameseExample: 'Tôi quét sàn nhà mỗi ngày.',
      koreanExample: '저는 매일 바닥을 쓸고 닦습니다.',
    },
    {
      vietnamese: 'thêm',
      korean: '추가하다',
      vietnameseExample: 'Tôi thêm đường vào cà phê.',
      koreanExample: '저는 커피에 설탕을 추가합니다.',
    },
    {
      vietnamese: 'bớt',
      korean: '줄이다',
      vietnameseExample: 'Tôi bớt muối trong món ăn.',
      koreanExample: '저는 요리에서 소금을 줄입니다.',
    },
    {
      vietnamese: 'nuôi',
      korean: '기르다',
      vietnameseExample: 'Tôi nuôi một con mèo.',
      koreanExample: '저는 고양이 한 마리를 기릅니다.',
    },
    {
      vietnamese: 'trồng',
      korean: '심다',
      vietnameseExample: 'Tôi trồng hoa trong vườn.',
      koreanExample: '저는 정원에 꽃을 심습니다.',
    },
    {
      vietnamese: 'hái',
      korean: '따다',
      vietnameseExample: 'Tôi hái táo trong vườn.',
      koreanExample: '저는 정원에서 사과를 따요.',
    },
    {
      vietnamese: 'nếm',
      korean: '맛보다',
      vietnameseExample: 'Tôi nếm món ăn mới.',
      koreanExample: '저는 새로운 요리를 맛봅니다.',
    },
    {
      vietnamese: 'bưng',
      korean: '나르다',
      vietnameseExample: 'Tôi bưng đĩa thức ăn.',
      koreanExample: '저는 음식 접시를 나릅니다.',
    },
    {
      vietnamese: 'đánh',
      korean: '치다',
      vietnameseExample: 'Tôi đánh răng mỗi ngày.',
      koreanExample: '저는 매일 이를 닦습니다.',
    },
    {
      vietnamese: 'đá',
      korean: '차다',
      vietnameseExample: 'Anh ấy đá bóng rất giỏi.',
      koreanExample: '그는 축구를 매우 잘합니다.',
    },
    {
      vietnamese: 'ôm',
      korean: '안다',
      vietnameseExample: 'Tôi ôm bạn khi gặp lại.',
      koreanExample: '저는 다시 만날 때 친구를 안아줍니다.',
    },
    {
      vietnamese: 'thắng',
      korean: '이기다',
      vietnameseExample: 'Đội của tôi thắng trận đấu.',
      koreanExample: '우리 팀이 경기에서 이겼습니다.',
    },
    {
      vietnamese: 'thua',
      korean: '지다',
      vietnameseExample: 'Tôi thua ván cờ.',
      koreanExample: '저는 체스 게임에서 졌습니다.',
    },
    {
      vietnamese: 'thở',
      korean: '숨 쉬다',
      vietnameseExample: 'Tôi thở sâu khi tập yoga.',
      koreanExample: '저는 요가를 할 때 깊게 숨을 쉽니다.',
    },
    {
      vietnamese: 'săn',
      korean: '사냥하다',
      vietnameseExample: 'Người xưa săn thú để kiếm thức ăn.',
      koreanExample: '옛날 사람들은 음식을 구하기 위해 동물을 사냥했습니다.',
    },
    {
      vietnamese: 'nhịn',
      korean: '참다',
      vietnameseExample: 'Tôi nhịn ăn buổi sáng.',
      koreanExample: '저는 아침 식사를 거릅니다.',
    },
    {
      vietnamese: 'bỏ',
      korean: '버리다',
      vietnameseExample: 'Tôi bỏ thói quen xấu.',
      koreanExample: '저는 나쁜 습관을 버립니다.',
    },
  ],

  /**
   * 중간 난이도 (TOPIK 3-4 수준의 단어)
   */
  intermediate: [
    // 여기에 중간 난이도 단어들을 추가할 수 있습니다
  ],

  /**
   * 어려운 난이도 (TOPIK 5-6 수준의 단어)
   */
  advanced: [
    // 여기에 어려운 난이도 단어들을 추가할 수 있습니다
  ],
};

